### ISSUE TITLE
64-bit build instructions

### ISSUE THREAD

**Issue by Venorcis** [JNIBWAPI/JNIBWAPI#7]
The 64 bit build notes.txt do not make any sense to me unfortunately

**Comment by phoglenix** [comment]
These were mostly notes to myself on what I had to do to get the bwta / bwapi DLLs to compile in x86_64.
The compiled DLLs are included in the repo so hopefully you won't have to repeat the process.
Also, BWAPI seems to be more stable in 32 bit anyway, so I'd only recommend the 64bit version if you're going to need >4GB RAM.
Let me know if there's any specific thing I should clarify in the notes.
